#!/bin/bash
# Configure CoTURN Server for Camera Platform
# This script creates a proper turnserver.conf with correct domain settings

set -e  # Exit on error

echo "============================================"
echo "CoTURN Server Configuration"
echo "============================================"
echo ""

# Check if running with sudo
if [ "$EUID" -ne 0 ]; then
    echo "❌ This script must be run with sudo"
    echo "Usage: sudo ./scripts/configure_turn_server.sh"
    exit 1
fi

# Get the actual user (not root when using sudo)
ACTUAL_USER="${SUDO_USER:-$USER}"

# Get project root
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"

echo "📋 Configuration:"
echo "   Project: $PROJECT_ROOT"
echo ""

# Check if .env exists
if [ ! -f "$ENV_FILE" ]; then
    echo "❌ Error: .env file not found at $ENV_FILE"
    echo "💡 Run setup_platform.py first to generate .env file"
    exit 1
fi

# Detect domain and IPs from .env
DOMAIN=$(grep -E "^EMQX_BROKER_ENDPOINT=" "$ENV_FILE" | cut -d'=' -f2 | tr -d ' "' || true)
TURN_URL=$(grep -E "^TURN_SERVER_URL=" "$ENV_FILE" | cut -d'=' -f2 | tr -d ' "' || true)
TURN_USERNAME=$(grep -E "^TURN_SERVER_USERNAME=" "$ENV_FILE" | cut -d'=' -f2 | tr -d ' "' || true)
TURN_PASSWORD=$(grep -E "^TURN_SERVER_PASSWORD=" "$ENV_FILE" | cut -d'=' -f2 | tr -d ' "' || true)

if [ -z "$DOMAIN" ]; then
    echo "❌ Error: Could not detect domain from .env"
    echo "Please set EMQX_BROKER_ENDPOINT in .env"
    exit 1
fi

# Get server IPs
echo "Detecting server IP addresses..."
LOCAL_IP=$(ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | grep -v '127.0.0.1' | head -1)

# Try to detect external IP
EXTERNAL_IP=$(curl -s --max-time 5 ifconfig.me 2>/dev/null || echo "")

if [ -z "$EXTERNAL_IP" ]; then
    echo "⚠️  Could not auto-detect external IP"
    read -p "Enter your external IP address: " EXTERNAL_IP
fi

echo ""
echo "📋 Detected Configuration:"
echo "   Domain: $DOMAIN"
echo "   Local IP: $LOCAL_IP"
echo "   External IP: $EXTERNAL_IP"
echo "   TURN Username: ${TURN_USERNAME:-turnuser}"
echo ""

# Verify with user
read -p "Is this correct? (yes/no): " confirm
if [ "$confirm" != "yes" ]; then
    echo "❌ Configuration cancelled"
    exit 1
fi

# Check if certificates exist
CERT_FILE="/etc/letsencrypt/live/$DOMAIN/fullchain.pem"
KEY_FILE="/etc/letsencrypt/live/$DOMAIN/privkey.pem"

if [ ! -f "$CERT_FILE" ]; then
    echo ""
    echo "⚠️  WARNING: SSL certificates not found at $CERT_FILE"
    echo "CoTURN will be configured but won't start until certificates are available"
    echo ""
fi

# Backup existing config
TURN_CONF="/etc/turnserver.conf"
if [ -f "$TURN_CONF" ]; then
    BACKUP="$TURN_CONF.backup.$(date +%Y%m%d_%H%M%S)"
    cp "$TURN_CONF" "$BACKUP"
    echo "✅ Backed up existing config to: $BACKUP"
fi

# Create new turnserver.conf
echo "📝 Creating turnserver configuration..."

cat > "$TURN_CONF" << EOF
# CoTURN Configuration for Camera Platform
# Auto-generated by configure_turn_server.sh
# Domain: $DOMAIN
# Generated: $(date)

# Listening ports
listening-port=3478
tls-listening-port=5349

# IP addresses
listening-ip=$LOCAL_IP
external-ip=$EXTERNAL_IP/$LOCAL_IP

# Port range for relay connections
min-port=49152
max-port=65535

# Server identification
server-name=$DOMAIN
realm=$DOMAIN

# Credentials
lt-cred-mech
user=${TURN_USERNAME:-turnuser}:${TURN_PASSWORD:-changeme}

# SSL Certificates
cert=$CERT_FILE
pkey=$KEY_FILE

# Logging
verbose
log-file=/var/tmp/turn.log
syslog

# Security and optimization
no-multicast-peers
no-cli
no-rfc5780
no-stun-backward-compatibility
response-origin-only-with-rfc5780

# Fingerprinting (required for WebRTC)
fingerprint

# Deny private IP addresses from being relayed
no-loopback-peers
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=172.16.0.0-172.31.255.255

# Database (optional - for persistent users)
# userdb=/var/lib/turn/turndb
EOF

echo "✅ Created turnserver configuration"
echo ""

# Set correct permissions
chmod 644 "$TURN_CONF"
echo "✅ Set permissions on turnserver.conf"
echo ""

# Enable turnserver in default config
if [ -f "/etc/default/coturn" ]; then
    if grep -q "^#TURNSERVER_ENABLED=1" /etc/default/coturn; then
        sed -i 's/^#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn
        echo "✅ Enabled turnserver in /etc/default/coturn"
    elif grep -q "^TURNSERVER_ENABLED=1" /etc/default/coturn; then
        echo "✅ Turnserver already enabled in /etc/default/coturn"
    else
        echo "TURNSERVER_ENABLED=1" >> /etc/default/coturn
        echo "✅ Enabled turnserver in /etc/default/coturn"
    fi
fi

# Show configuration summary
echo "============================================"
echo "📋 CoTURN Configuration Summary"
echo "============================================"
echo ""
echo "Domain/Realm:   $DOMAIN"
echo "Listening IP:   $LOCAL_IP"
echo "External IP:    $EXTERNAL_IP"
echo "TURN Port:      3478 (UDP/TCP)"
echo "TURN TLS Port:  5349 (TCP)"
echo "Relay Ports:    49152-65535 (UDP)"
echo ""
echo "Username:       ${TURN_USERNAME:-turnuser}"
echo "Password:       ${TURN_PASSWORD:-changeme}"
echo ""
echo "Certificates:   $CERT_FILE"
echo "                $KEY_FILE"
echo ""

# Start/Restart service
echo "============================================"
echo "Starting CoTURN Service"
echo "============================================"
echo ""

if [ -f "$CERT_FILE" ] && [ -f "$KEY_FILE" ]; then
    systemctl restart coturn
    sleep 2

    if systemctl is-active --quiet coturn; then
        echo "✅ CoTURN service started successfully"
        systemctl enable coturn
        echo "✅ CoTURN service enabled (will start on boot)"
    else
        echo "❌ CoTURN service failed to start"
        echo "Check logs: sudo journalctl -u coturn -n 50"
        exit 1
    fi
else
    echo "⚠️  Skipping service start - SSL certificates not available yet"
    echo "💡 Run this script again after obtaining SSL certificates"
fi

echo ""
echo "============================================"
echo "✅ CoTURN Configuration Complete!"
echo "============================================"
echo ""
echo "📌 Next steps:"
echo "   1. Ensure ports are forwarded in router:"
echo "      - 3478 (UDP+TCP) → $LOCAL_IP:3478"
echo "      - 5349 (TCP) → $LOCAL_IP:5349"
echo "      - 49152-65535 (UDP) → $LOCAL_IP:49152-65535"
echo ""
echo "   2. Test TURN server:"
echo "      nc -zv $DOMAIN 5349"
echo ""
echo "   3. Check logs:"
echo "      sudo journalctl -u coturn -f"
echo ""
echo "   4. Update .env with TURN settings:"
echo "      TURN_SERVER_URL=turns:$DOMAIN:5349"
echo "      TURN_SERVER_USERNAME=${TURN_USERNAME:-turnuser}"
echo "      TURN_SERVER_PASSWORD=${TURN_PASSWORD:-changeme}"
echo ""
echo "📖 See DEPLOYMENT_GUIDE.md for firewall configuration"
echo ""
